### ISSUE TITLE
JsonNettyStreamingService does not shutdown all nio threads correctly and application can't be stopped after disposing and disconnecting because stuck nio thread alive

### ISSUE THREAD

**Issue by pchertalev** [bitrich-info/xchange-stream#145]
I tested several exchanges who use JsonNettyStreamingService like BitfinexManualExample, OkCoinManualExample, ...  etc

No one of these tests can stop after disposing and disconnecting.

I have checked thread dump there is alive nio thread after disconneting:

"nioEventLoopGroup-2-1" #14 prio=10 os_prio=2 tid=0x000000002a637800 nid=0x1860 runnable [0x000000002c16e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000005c11cf628> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000005c11d0760> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000005c11d0650> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by badgerwithagun** [comment]
This may be solved by #191

**Comment by pchertalev** [comment]
solved by #191
