### ISSUE TITLE
BitstampManualExample not working

### ISSUE THREAD

**Issue by davidjirovec** [bitrich-info/xchange-stream#201]
```
17:35:23.867 [pusher-java-client eventQueue] INFO  info.bitrich.xchangestream.service.pusher.PusherStreamingService - State changed to DISCONNECTING from CONNECTED
io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
Exception in thread "pusher-java-client eventQueue" io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
Exception in thread "pusher-java-client eventQueue" io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
Exception in thread "pusher-java-client eventQueue" io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
```

**Comment by jurepetrovic** [comment]
Did you come to any conclusion? 
I'm getting similar error, but I'd like that my app survives network problems.

Thanks, 
Jure
