### ISSUE TITLE
example fails with Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state

### ISSUE THREAD

**Issue by crowlogic** [bitrich-info/xchange-stream#240]
19:52:08.823 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
19:52:08.825 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
19:52:09.055 [default] [main] DEBUG si.mazi.rescu.Config - Configuration from rescu.properties: 
19:52:09.055 [default] [main] DEBUG si.mazi.rescu.Config - httpConnTimeout = 30000 
19:52:09.056 [default] [main] DEBUG si.mazi.rescu.Config - httpReadTimeout = 30000 
19:52:09.056 [default] [main] DEBUG si.mazi.rescu.Config - proxyHost = null 
19:52:09.056 [default] [main] DEBUG si.mazi.rescu.Config - proxyPort = null 
19:52:09.056 [default] [main] DEBUG si.mazi.rescu.Config - ignoreHttpErrorCodes = false 
ExchangeMetaData [currencyPairs={BTC/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.00085000, maximumAmount=null, priceScale=2], BTC/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.00085000, maximumAmount=null, priceScale=2], EUR/USD=CurrencyPairMetaData [tradingFee=0.0020, minimumAmount=5.00, maximumAmount=null, priceScale=5], XRP/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=10.00000000, maximumAmount=null, priceScale=5], XRP/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=11.00000000, maximumAmount=null, priceScale=5], XRP/BTC=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=15.00000000, maximumAmount=null, priceScale=8], LTC/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.04000000, maximumAmount=null, priceScale=2], LTC/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.04500000, maximumAmount=null, priceScale=2], LTC/BTC=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.06000000, maximumAmount=null, priceScale=8], ETH/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.01500000, maximumAmount=null, priceScale=2], ETH/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.01500000, maximumAmount=null, priceScale=2], ETH/BTC=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.02000000, maximumAmount=null, priceScale=8], BCH/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.00700000, maximumAmount=null, priceScale=2], BCH/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.00600000, maximumAmount=null, priceScale=2], BCH/BTC=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.01000000, maximumAmount=null, priceScale=8]}, currencies={BTC=CurrencyMetaData [scale=8, withdrawalFee=0], USD=CurrencyMetaData [scale=2, withdrawalFee=0], EUR=CurrencyMetaData [scale=2, withdrawalFee=0], XRP=CurrencyMetaData [scale=8, withdrawalFee=0], LTC=CurrencyMetaData [scale=8, withdrawalFee=0], ETH=CurrencyMetaData [scale=8, withdrawalFee=0], BCH=CurrencyMetaData [scale=8, withdrawalFee=0]}, publicRateLimits=null, privateRateLimits=[RateLimit [calls=60, timeSpan=0, timeUnit=MINUTES]], shareRateLimits=true]
io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
Exception in thread "pusher-java-client eventQueue" io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:92)
	at info.bitrich.xchangestream.service.pusher.PusherStreamingService$1.onError(PusherStreamingService.java:56)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:232)
	at com.pusher.client.util.Factory$1.run(Factory.java:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: No exception found: [code: null], message: Cannot send a message while in DISCONNECTING state
	... 6 more
Oct 18, 2018 7:52:09 PM b2tf.data.StreamingBitstampDemo lambda$1
INFO: Disconnected from the Exchange

**Comment by Flemingjp** [comment]
Can anyone replicate this issue? @crowlogic if you could share a gist of your code maybe?

**Comment by badgerwithagun** [comment]
Closing as stale. Please re-open if this is still an issue.
