### ISSUE TITLE
BitMex getBalances() java.lang.NullPointerException

### ISSUE THREAD

**Issue by mdvx** [bitrich-info/xchange-stream#264]
Using the alternate Exchange code works:

```java
public class Main {

    public static void main(String[] args) throws Exception {
        CertHelper.trustAllCerts();
        StreamingExchange exchange = StreamingExchangeFactory.INSTANCE.createExchangeWithoutSpecification(BitmexStreamingExchange.class.getName());

        //Exchange exchange = ExchangeFactory.INSTANCE.createExchange(BitmexExchange.class);
        final ExchangeSpecification exSpec = exchange.getDefaultExchangeSpecification();
        exSpec.setApiKey("tTsudUH-oOI302qHmu3aU8M9");
        exSpec.setSecretKey("8sl4KO3Zxr6bgIAlUqtMZOZNgeCqQhv9t6E105rtLqRRz6UB");
        exSpec.setExchangeSpecificParametersItem(StreamingExchange.USE_SANDBOX, true);
        exSpec.setShouldLoadRemoteMetaData(true);
        exchange.applySpecification(exSpec);

        exchange.connect().blockingAwait();

        //AccountService accountService = exchange.getAccountService();
        //AccountInfo accountInfo = accountService.getAccountInfo();
        //System.out.println(accountInfo.toString());

        exchange.getAccountService().getAccountInfo().getWallet().getBalances();
    }
}
```

And the error:

```
"C:\Program Files\Java\jdk-10.0.2\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:61616,suspend=y,server=n -Dvisualvm.id=91635624514300 -javaagent:C:\Users\Marc\.IntelliJIdea2018.3\system\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "T:\bitmex-test\out\production\bitmex-test;C:\Users\Marc\.m2\repository\info\bitrich\xchange-stream\xchange-stream-core\4.3.11\xchange-stream-core-4.3.11.jar;C:\Users\Marc\.m2\repository\info\bitrich\xchange-stream\service-core\4.3.11\service-core-4.3.11.jar;C:\Users\Marc\.m2\repository\info\bitrich\xchange-stream\service-netty\4.3.11\service-netty-4.3.11.jar;C:\Users\Marc\.m2\repository\io\netty\netty-all\4.1.21.Final\netty-all-4.1.21.Final.jar;C:\Users\Marc\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.5\jackson-databind-2.9.5.jar;C:\Users\Marc\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.0\jackson-annotations-2.9.0.jar;C:\Users\Marc\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.9.5\jackson-core-2.9.5.jar;C:\Users\Marc\.m2\repository\org\knowm\xchange\xchange-core\4.3.11\xchange-core-4.3.11.jar;C:\Users\Marc\.m2\repository\com\github\mmazi\rescu\2.0.2\rescu-2.0.2.jar;C:\Users\Marc\.m2\repository\javax\ws\rs\javax.ws.rs-api\2.1\javax.ws.rs-api-2.1.jar;C:\Users\Marc\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Marc\.m2\repository\oauth\signpost\signpost-core\1.2.1.2\signpost-core-1.2.1.2.jar;C:\Users\Marc\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\Marc\.m2\repository\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;C:\Users\Marc\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;C:\Users\Marc\.m2\repository\org\slf4j\slf4j-api\1.7.13\slf4j-api-1.7.13.jar;C:\Users\Marc\.m2\repository\io\reactivex\rxjava2\rxjava\2.0.9\rxjava-2.0.9.jar;C:\Users\Marc\.m2\repository\org\reactivestreams\reactive-streams\1.0.0\reactive-streams-1.0.0.jar;C:\Users\Marc\.m2\repository\info\bitrich\xchange-stream\xchange-bitmex\4.3.11\xchange-bitmex-4.3.11.jar;C:\Users\Marc\.m2\repository\org\knowm\xchange\xchange-bitmex\4.3.11\xchange-bitmex-4.3.11.jar;C:\Users\Marc\.m2\repository\com\google\guava\guava\25.1-jre\guava-25.1-jre.jar;C:\Users\Marc\.m2\repository\org\checkerframework\checker-qual\2.0.0\checker-qual-2.0.0.jar;C:\Users\Marc\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar;C:\Users\Marc\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\Marc\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.3\lib\idea_rt.jar" com.company.Main
Connected to the target VM, address: '127.0.0.1:61616', transport: 'socket'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.bitmex.service.BitmexDigest.digestParams(BitmexDigest.java:45)
	at si.mazi.rescu.Params.digestAll(Params.java:199)
	at si.mazi.rescu.RestInvocation.create(RestInvocation.java:147)
	at si.mazi.rescu.RestInvocationHandler.createInvocation(RestInvocationHandler.java:188)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:116)
	at com.sun.proxy.$Proxy10.getAccount(Unknown Source)
	at org.knowm.xchange.bitmex.service.BitmexAccountServiceRaw.getBitmexAccountInfo(BitmexAccountServiceRaw.java:33)
	at org.knowm.xchange.bitmex.service.BitmexAccountService.getAccountInfo(BitmexAccountService.java:28)
	at com.company.Main.main(Main.java:37)

```
![image](https://user-images.githubusercontent.com/2664983/50037543-7e359c80-ffe0-11e8-9f80-a658849e9b84.png)

**Comment by mdvx** [comment]
I have not seen this problem again in several months

**Comment by declan94** [comment]
I've encountered the same problem

**Comment by declan94** [comment]
I've solved the problem. 

It is because the `BitmexStreamingExchange` overrides the `BaseExchange`'s `getNonceFactory` method and returns `null` Incorrectly
