### ISSUE TITLE
Bitfinex fails to subscribe to DASH

### ISSUE THREAD

**Issue by awsfanatic** [bitrich-info/xchange-stream#33]
`DASH/BTC` and `DASH/USD` are listed as supported by `getExchangeSymbols()` for `BitfinexStreamingExchange`.

Any other pair works:
```scala
import info.bitrich.xchangestream.core.StreamingExchangeFactory
import info.bitrich.xchangestream.bitfinex.BitfinexStreamingExchange
import org.knowm.xchange.currency.CurrencyPair
import org.knowm.xchange.dto.marketdata.Trade

object Tst extends App {
  val pair = new CurrencyPair("BTC", "USD")
  val exchange = StreamingExchangeFactory.INSTANCE.createExchange(classOf[BitfinexStreamingExchange].getName)

  exchange.connect.blockingAwait()

  exchange.getStreamingMarketDataService.getTrades(pair).subscribe((trade: Trade) => {
    println(trade)
  }, (throwable: Throwable) => println("ERROR in getting trades: ", pair, throwable))
}
```

Same code with DASH won't work:
```scala
import info.bitrich.xchangestream.core.StreamingExchangeFactory
import info.bitrich.xchangestream.bitfinex.BitfinexStreamingExchange
import org.knowm.xchange.currency.CurrencyPair
import org.knowm.xchange.dto.marketdata.Trade

object Tst extends App {
  val pair = new CurrencyPair("DASH", "USD")
  val exchange = StreamingExchangeFactory.INSTANCE.createExchange(classOf[BitfinexStreamingExchange].getName)
 
  exchange.connect.blockingAwait()

  exchange.getStreamingMarketDataService.getTrades(pair).subscribe((trade: Trade) => {
    println(trade)
  }, (throwable: Throwable) => println("ERROR in getting trades: ", pair, throwable))
}
```

Exception:
```
java.lang.NullPointerException
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.getChannelNameFromMessage(BitfinexStreamingService.java:104)
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.getChannelNameFromMessage(BitfinexStreamingService.java:20)
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.getChannel(NettyStreamingService.java:199)
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.handleError(NettyStreamingService.java:213)
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.handleMessage(BitfinexStreamingService.java:88)
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.messageHandler(BitfinexStreamingService.java:54)
	at info.bitrich.xchangestream.service.netty.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:66)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1267)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

I could probably fix it myself if pointed in the right direction.

**Comment by lukaszaoralek** [comment]
@awsfanatic 
change symbol "DASH" for the currency DASH to "DSH", for example:
`CurrencyPair dashBtc = new CurrencyPair("DSH", "USD");`

let me know, if does it work for you now

**Comment by awsfanatic** [comment]
@lukaszaoralek 
Yes, this works:
`val pair = new CurrencyPair("DSH", "USD")`

This doesn't:
`val pair = CurrencyPair.DASH_BTC`

Any walkaround?

**Comment by lukaszaoralek** [comment]
@awsfanatic 
There is no workaround, the exchange doesn't use symbol "DASH" for DASH currency, but "DSH". You have to use `new CurrencyPair("DSH", "USD")`.

**Comment by awsfanatic** [comment]
@lukaszaoralek But `getExchangeSymbols` reports `DASH/USD`, not `DSH/USD`. So I guess there is some sort of internal conversion/normalization in place.

**Comment by lukaszaoralek** [comment]
@awsfanatic please, go to [bitfinex dash tradeview](https://www.bitfinex.com/t/DASH:USD) page, enable developer tools from your web browser, click on the network tab and ws connection and check it yourself:
`{"event":"subscribe","pair":"DSHUSD","channel":"book","prec":"P1","freq":"F0"}`

bitfinex uses only 3 characters string for the currency name.

**Comment by dozd** [comment]
@awsfanatic I see your point. `getXchangeSymbols` are called in [Xchange](https://github.com/timmolter/XChange) library so I advice create PR or issue there. It won't be hard to fix.

**Comment by lukaszaoralek** [comment]
@dozd I'm not sure if is it good idea to change behavior `CurrencyPair.DASH_BTC` because there are also exists exchanges (such as Poloniex) where they use "DASH" for DASH currency. Therefore you can create `new CurrencyPair("DSH", "USD)"` manually to solve it.

**Comment by dozd** [comment]
@lukaszaoralek Yeah, exactly. Metadata for Bitfinex should contain correct CurrencyPair.
