### ISSUE TITLE
No netty-tcnative

### ISSUE THREAD

**Issue by sirolf2009** [bitrich-info/xchange-stream#37]
Hello, I'm trying to get either 4.2.3 or 4.3.0-SNAPSHOT to work, but both result in an issue with netty not being available.

Full log at: https://pastebin.com/NCmFhyZ6

Relevant bits:
```
2017-11-21 13:05:24,613 [DEBUG ] NativeLibraryLoader 81 │ Unable to load the library 'netty-tcnative-linux-x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty-tcnative-linux-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_151]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_151]
	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_151]
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-common-4.0.47.Final.jar:4.0.47.Final]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:272) ~[netty-common-4.0.47.Final.jar:4.0.47.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:264) ~[netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:252) ~[netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:199) ~[netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:170) ~[netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:403) ~[netty-handler-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:85) ~[netty-handler-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.handler.ssl.SslContext.defaultProvider(SslContext.java:118) ~[netty-handler-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.handler.ssl.SslContext.defaultClientProvider(SslContext.java:114) ~[netty-handler-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:763) ~[netty-handler-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:446) ~[netty-handler-4.0.47.Final.jar:4.0.47.Final]
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.lambda$connect$2(NettyStreamingService.java:83) ~[service-netty-4.3.0-SNAPSHOT.jar:?]
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39) [rxjava-2.0.4.jar:2.0.4]
	at io.reactivex.Completable.subscribe(Completable.java:1613) [rxjava-2.0.4.jar:2.0.4]
	at io.reactivex.Completable.blockingAwait(Completable.java:909) [rxjava-2.0.4.jar:2.0.4]
	at com.sirolf2009.orderbook.collector.OrderbookCollector.run(OrderbookCollector.java:16) [classes/:?]
	at com.sirolf2009.orderbook.collector.OrderbookCollector.main(OrderbookCollector.java:25) [classes/:?]
2017-11-21 13:05:24,616 [DEBUG ] NativeLibraryLoader 81 │ Unable to load the library 'netty-tcnative-linux-x86_64', trying next name...
java.lang.UnsatisfiedLinkError: no netty-tcnative-linux-x86_64 in java.library.path
```
It tries a few more names until resulting to
```
2017-11-21 13:05:24,622 [DEBUG ] OpenSsl 91 │ Failed to initialize netty-tcnative; OpenSslEngine will be unavailable. See http://netty.io/wiki/forked-tomcat-native.html for more information.
```
It eventually crashes with
```
2017-11-21 13:05:24,842 [WARN  ] ChannelInitializer 151 │ Failed to initialize a channel. Closing: [id: 0xb9e45b6d]
java.lang.NoSuchMethodError: io.netty.handler.codec.compression.ZlibCodecFactory.isSupportingWindowSizeAndMemLevel()Z
	at info.bitrich.xchangestream.gdax.netty.WebSocketClientCompressionAllowClientNoContextHandler.<init>(WebSocketClientCompressionAllowClientNoContextHandler.java:22) ~[xchange-gdax-4.3.0-SNAPSHOT.jar:?]
	at info.bitrich.xchangestream.gdax.netty.WebSocketClientCompressionAllowClientNoContextHandler.<clinit>(WebSocketClientCompressionAllowClientNoContextHandler.java:18) ~[xchange-gdax-4.3.0-SNAPSHOT.jar:?]
	at info.bitrich.xchangestream.gdax.GDAXStreamingService.getWebSocketClientExtensionHandler(GDAXStreamingService.java:102) ~[xchange-gdax-4.3.0-SNAPSHOT.jar:?]
	at info.bitrich.xchangestream.service.netty.NettyStreamingService$1.initChannel(NettyStreamingService.java:105) ~[service-netty-4.3.0-SNAPSHOT.jar:?]
	at info.bitrich.xchangestream.service.netty.NettyStreamingService$1.initChannel(NettyStreamingService.java:97) ~[service-netty-4.3.0-SNAPSHOT.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:582) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:43) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1347) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1082) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:632) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:452) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:374) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-11-21 13:05:24,845 [WARN  ] DefaultPromise 151 │ An exception was thrown by info.bitrich.xchangestream.service.netty.NettyStreamingService$$Lambda$4/405896924.operationComplete()
java.lang.NullPointerException: null
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.lambda$null$1(NettyStreamingService.java:117) ~[service-netty-4.3.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:851) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(AbstractChannel.java:834) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:194) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1226) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:539) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:524) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:506) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:970) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:214) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:166) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.0.47.Final.jar:4.0.47.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
pom.xml (relevant bits, full at https://pastebin.com/2zHZvLMN)
```
(snip)
		<extensions>
			<extension>
				<groupId>kr.motd.maven</groupId>
				<artifactId>os-maven-plugin</artifactId>
				<version>1.4.0.Final</version>
			</extension>
		</extensions>
(snip)
		<dependency>
			<groupId>info.bitrich.xchange-stream</groupId>
			<artifactId>xchange-stream-core</artifactId>
			<version>4.3.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>info.bitrich.xchange-stream</groupId>
			<artifactId>xchange-gdax</artifactId>
			<version>4.3.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative</artifactId>
			<version>2.0.0.Final</version>
			<classifier>linux-x86_64</classifier>
		</dependency>
(snip)
```
As you can see I tried to follow the guide from http://netty.io/wiki/forked-tomcat-native.html, but to no avail

also, this might help
```
$ cat /proc/version
Linux version 4.9.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.51-1 (2017-09-28)
```

**Comment by dozd** [comment]
I'm not sure I can help you with something that is out of scope of this library. It should be use without any external netty dependency because it's already included in exchanges when needed.

I don't know why you need another `netty-tcnative` in your project. Sorry I can't probably help you as it seems there is no problem in the xchange-stream. Try remove that dependency because that null pointer seems like dependency conflict to me.

**Comment by sirolf2009** [comment]
Alright, so to test that theory, I copied my project to a different pc, but it showed the same error. So it had to had been a configuration error. I then realized that the cassandra driver comes with it's own netty version as well. Removing the cassandra dependency fixed it. Cheers
