### ISSUE TITLE
BitFinex error response throws NullPointerException

### ISSUE THREAD

**Issue by janakerman** [bitrich-info/xchange-stream#49]
As mentioned in issue #48 invalid symbol errors are not handled correctly when subscribing to BitFinex. A null exception is thrown:

```
java.lang.NullPointerException
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.getChannelNameFromMessage(BitfinexStreamingService.java:104)
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.getChannelNameFromMessage(BitfinexStreamingService.java:20)
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.getChannel(NettyStreamingService.java:199)
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.handleError(NettyStreamingService.java:213)
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.handleMessage(BitfinexStreamingService.java:88)
	at info.bitrich.xchangestream.bitfinex.BitfinexStreamingService.messageHandler(BitfinexStreamingService.java:54)
	at info.bitrich.xchangestream.service.netty.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:66)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1172)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.base/java.lang.Thread.run(Thread.java:844)```

Looks like an array (a normal ticker response) is expected, but in fact the response is an ObjectNode.

**Comment by janakerman** [comment]
Looking into this a little more. Here's the message sequence for a known currency pair.
Request:
```
{
  "event": "subscribe",
  "channel": "ticker",
  "symbol": "tBTCUSD"
}
```
Confirmation response:
```
{
  "event": "subscribed",
  "channel": "ticker",
  "chanId": 5,
  "symbol": "tBTCUSD",
  "pair": "BTCUSD"
}
```
Tick:
```
[
  5,
  [
    17720,
    168.62971719,
    17721,
    58.05468552,
    1560.76377539,
    0.0966,
    17720,
    61569.19890728,
    18111,
    16104
  ]
]
```

Here's the error sequence:
Request:
```
{
  "event": "subscribe",
  "channel": "ticker",
  "symbol": "DASHUSD"
}
```
Response:
```
{
  "channel": "ticker",
  "symbol": "DASHUSD",
  "event": "error",
  "msg": "symbol: invalid",
  "code": 10300,
  "pair": "ASHUSD"
}
```

The exception actually happens inside of some error handling logic. It tries to get the channel name from the message, which fails as the error response has neither a CHANNEL_ID property, nor is it an array.

```
    protected String getChannelNameFromMessage(JsonNode message) throws IOException {
        String chanId;
        if (message.has(CHANNEL_ID)) {
            chanId = message.get(CHANNEL_ID).asText();
        } else {
            chanId = message.get(0).asText();
        }

        if (chanId == null) throw new IOException("Can't find CHANNEL_ID value");
        return subscribedChannels.get(chanId);
    }
```

Since the error occurs in the else block, we never get to the IOException, so it never gets to the catch block in the outer function calls, and bubbles up and is not caught then eventually the channel is closed (`ChannelOutboundInvoker::close`). This seems to cause the websocket to disconnect.

**Comment by dozd** [comment]
#49
