### ISSUE TITLE
Binance example throws NullPointerException

### ISSUE THREAD

**Issue by aacdevelop** [bitrich-info/xchange-stream#74]
Tried launching Binance code under the test directory and got this stacktrace:

java.lang.NullPointerException
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.handleChannelMessage(NettyStreamingService.java:241)
	at info.bitrich.xchangestream.service.netty.NettyStreamingService.handleMessage(NettyStreamingService.java:231)
	at info.bitrich.xchangestream.binance.BinanceProductStreamingService.messageHandler(BinanceProductStreamingService.java:39)
	at info.bitrich.xchangestream.service.netty.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:66)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at ...

**Comment by pesua** [comment]
Hi, this was fixed in #53 
See discussion #49
